### ISSUE TITLE
Pairing issues 

### ISSUE THREAD

**Issue by magnip** [HomeKidd/ESP8266-HomeKit-Stateless-Button-Elgato-Eve-Button#1]
Hi first off thanks for your continued work on all your HomeKit projects.
I’m having a issue with final step it won’t pair with home app. I can see it and have scanned code + entered pin but still nothing. I’m using a Sonoff basic if that’s the issue? Reset works fine connecting to api with password 12345678 works as it should add my WiFi details, removed power then power back up both eve app and home app detect device HomeKid-E499D7 try to pair but nothing. Any help would be appreciated.

**Comment by HomeKidd** [comment]
Hi! Thanks 👌
Yes the issue is with the Sonoff. Sonoff has 1MB flash but my code is for devices with 4MB flash. HomeKit cant erase the flash sector 0x100000 because it doesnt exist on devices with 1MB flash size. 

The solution is to use devices with 4MB flash (eg Wemos) and flash it with **--fs 4M** 👌
