### ISSUE TITLE
Not using button shield

### ISSUE THREAD

**Issue by ChopsKingsland** [HomeKidd/ESP8266-HomeKit-Stateless-Button-Elgato-Eve-Button#3]
I want to make this, but I want to know if there is a way I can use any button I want, instead of the button shield

**Comment by HomeKidd** [comment]
Hi! You can use any button you want, but keep in mind that the button has to be connected to `GPIO0` and `GND` 👌

**Comment by ChopsKingsland** [comment]
Thanks! Is there an easier way to setup, like a .ino file?

**Comment by ChopsKingsland** [comment]
And, is any sort of bridge needed, or does it connect directly to HomeKit?

**Comment by HomeKidd** [comment]
No, theres no .ino file since its based on [esp-homekit](https://github.com/maximkulkin/esp-homekit) and [esp-open-rtos](https://github.com/SuperHouse/esp-open-rtos) which is written in pure C, and its much more complicated then Arduino😄 This is why i'm not uploading the source code, most people simply cannot compile the code and using .bin files you have better chance 😄
 
And no, nothing else required, all of my projects are native HomeKit and not using any bridge/Raspberry Pi etc!

For your first question:
See my other projects, all of these have schematics how button is connected to `GPIO0` and `GND`. No pullup/pulldown resistors needed 😄

**Comment by ChopsKingsland** [comment]
is this also compatible with the ESP32, as that also has a temperature sensor that could be used for HomeKit?

**Comment by HomeKidd** [comment]
No, all of my projects is based on esp8266 as the repository name suggest 😄
For Temperature Sensor (Fake Eve Degree) i have an another repository, but thats also for ESP8266 and requires some other components for proper working
